--- #YAML:1.0
name:               App-DubiousHTTP
version:            0.005
abstract:           use ambiguous HTTP to circumvent security systems
author:
    - Steffen Ullrich <sullr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    AnyEvent:         6.12
    Net::PcapWriter:  0
resources:
    bugtracker:  https://rt.cpan.org/Dist/Display.html?Queue=App-DubiousHTTP
    homepage:    https://github.com/noxxi/p5-app-dubioushttp
    license:     http://dev.perl.org/licenses/
    repository:  https://github.com/noxxi/p5-app-dubioushttp
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
